CREATE TABLE `books` (
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`author` VARCHAR(50) NOT NULL,
	`section` VARCHAR(50) NOT NULL,
	`title` VARCHAR(50) NOT NULL,
	`date` DATE NOT NULL,
	`status` VARCHAR(50) NOT NULL,
	`summary` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `ID` (`ID`)
)
COLLATE='ujis_japanese_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;
